/*
 * AetherOS — initrd CPIO Reader
 * File: kernel/fs/initrd.c
 *
 * Parses the CPIO newc archive that is embedded in the kernel binary.
 * The archive is linked in via initrd.o (generated by objcopy -I binary).
 *
 * CPIO newc entry layout (all sizes in bytes):
 *   110   header (ASCII hex fields)
 *   N     filename (namesize bytes, includes NUL terminator)
 *   P1    padding to align (110+N) to 4-byte boundary
 *   D     file data (filesize bytes)
 *   P2    padding to align entire entry to 4-byte boundary
 *
 * The archive ends with a sentinel entry whose name is "TRAILER!!!".
 */

#include "aether/initrd.h"
#include "aether/printk.h"
#include "aether/types.h"

/* Symbols injected by: objcopy -I binary -O elf64-littleaarch64 initrd.cpio */
extern u8 _binary_initrd_cpio_start[];
extern u8 _binary_initrd_cpio_end[];

/* ── CPIO header (110-byte ASCII format) ────────────────────────── */

#define CPIO_HDR_SIZE  110
#define CPIO_MAGIC     "070701"

/* Raw header — all fields are 8-char ASCII hex, no NUL terminators */
struct cpio_hdr {
    char magic[6];
    char ino[8];
    char mode[8];
    char uid[8];
    char gid[8];
    char nlink[8];
    char mtime[8];
    char filesize[8];
    char devmajor[8];
    char devminor[8];
    char rdevmajor[8];
    char rdevminor[8];
    char namesize[8];
    char check[8];
} __attribute__((packed));

/* ── Helpers ────────────────────────────────────────────────────── */

static u32 hex8(const char *s)
{
    u32 v = 0;
    for (int i = 0; i < 8; i++) {
        char c = s[i];
        u32 d;
        if (c >= '0' && c <= '9')      d = (u32)(c - '0');
        else if (c >= 'a' && c <= 'f') d = (u32)(c - 'a') + 10u;
        else if (c >= 'A' && c <= 'F') d = (u32)(c - 'A') + 10u;
        else                            d = 0;
        v = (v << 4) | d;
    }
    return v;
}

static u32 align4(u32 v) { return (v + 3u) & ~3u; }

static int cpio_streq(const char *a, const char *b)
{
    while (*a && *b && *a == *b) { a++; b++; }
    return *a == *b;
}

/* Manual memory comparison (no libc available) */
static int cpio_memeq(const void *a, const void *b, u32 n)
{
    const u8 *pa = (const u8 *)a;
    const u8 *pb = (const u8 *)b;
    for (u32 i = 0; i < n; i++)
        if (pa[i] != pb[i]) return 0;
    return 1;
}

/* ── Public API ─────────────────────────────────────────────────── */

void initrd_init(void)
{
    uintptr_t size = (uintptr_t)(_binary_initrd_cpio_end -
                                  _binary_initrd_cpio_start);
    kinfo("initrd: CPIO archive at %p, %lu bytes\n",
          (void *)_binary_initrd_cpio_start, (unsigned long)size);

    /* Quick sanity check — verify the first magic */
    if (!cpio_memeq(_binary_initrd_cpio_start, CPIO_MAGIC, 6)) {
        kerror("initrd: bad magic — archive may be corrupt\n");
        return;
    }

    /* Walk entries and print a directory listing */
    const u8 *p   = _binary_initrd_cpio_start;
    const u8 *end = _binary_initrd_cpio_end;
    u32 count = 0;

    while (p + CPIO_HDR_SIZE <= end) {
        const struct cpio_hdr *h = (const struct cpio_hdr *)p;
        if (!cpio_memeq(h->magic, CPIO_MAGIC, 6)) break;

        u32 namesize = hex8(h->namesize);
        u32 filesize = hex8(h->filesize);
        const char *name = (const char *)(p + CPIO_HDR_SIZE);

        if (namesize >= 11 && cpio_memeq(name, "TRAILER!!!", 10))
            break;

        kinfo("initrd:   %s  (%lu bytes)\n",
              name, (unsigned long)filesize);
        count++;

        u32 data_off  = align4(CPIO_HDR_SIZE + namesize);
        u32 next_off  = align4(data_off + filesize);
        p += next_off;
    }

    kinfo("initrd: %lu file(s) listed\n", (unsigned long)count);
}

const void *initrd_find(const char *path, u32 *size_out)
{
    /* Strip a leading slash so "/init" and "init" both work */
    if (path[0] == '/') path++;

    const u8 *p   = _binary_initrd_cpio_start;
    const u8 *end = _binary_initrd_cpio_end;

    while (p + CPIO_HDR_SIZE <= end) {
        const struct cpio_hdr *h = (const struct cpio_hdr *)p;

        if (!cpio_memeq(h->magic, CPIO_MAGIC, 6)) {
            kerror("initrd: bad CPIO magic at %p\n", (void *)p);
            return NULL;
        }

        u32 namesize = hex8(h->namesize);
        u32 filesize = hex8(h->filesize);
        const char *name = (const char *)(p + CPIO_HDR_SIZE);

        /* End-of-archive sentinel */
        if (namesize >= 11 && cpio_memeq(name, "TRAILER!!!", 10))
            break;

        u32 data_off = align4(CPIO_HDR_SIZE + namesize);
        u32 next_off = align4(data_off + filesize);

        /* Compare, ignoring a leading "./" that some cpio variants add */
        const char *cmp = name;
        if (namesize >= 3 && name[0] == '.' && name[1] == '/')
            cmp += 2;

        if (cpio_streq(cmp, path)) {
            if (size_out) *size_out = filesize;
            return (const void *)(p + data_off);
        }

        p += next_off;
    }

    kerror("initrd: '%s' not found\n", path);
    return NULL;
}

u32 initrd_list(char *buf, u32 len)
{
    if (!buf || len == 0) return 0;

    const u8 *p   = _binary_initrd_cpio_start;
    const u8 *end = _binary_initrd_cpio_end;
    u32 out = 0;

    while (p + CPIO_HDR_SIZE <= end) {
        const struct cpio_hdr *h = (const struct cpio_hdr *)p;
        if (!cpio_memeq(h->magic, CPIO_MAGIC, 6)) break;

        u32 namesize = hex8(h->namesize);
        u32 filesize = hex8(h->filesize);
        const char *name = (const char *)(p + CPIO_HDR_SIZE);

        if (namesize >= 11 && cpio_memeq(name, "TRAILER!!!", 10))
            break;

        /* Write "name  <size> bytes\n" into buf */
        for (u32 i = 0; name[i] && out + 1 < len; i++)
            buf[out++] = name[i];
        /* pad name to column 16 */
        u32 col = 0; for (u32 i = 0; name[i]; i++) col++;
        for (; col < 16 && out + 1 < len; col++) buf[out++] = ' ';
        /* print size in decimal */
        char nbuf[12]; int ni = 0;
        u32 tmp = filesize;
        if (tmp == 0) { nbuf[ni++] = '0'; }
        else { while (tmp) { nbuf[ni++] = (char)('0' + tmp % 10); tmp /= 10; } }
        for (int k = ni - 1; k >= 0 && out + 1 < len; k--)
            buf[out++] = nbuf[k];
        /* " bytes\n" */
        const char *suf = " bytes\n";
        for (int k = 0; suf[k] && out + 1 < len; k++)
            buf[out++] = suf[k];

        u32 data_off = align4(CPIO_HDR_SIZE + namesize);
        u32 next_off = align4(data_off + filesize);
        p += next_off;
    }

    buf[out] = '\0';
    return out;
}

u32 initrd_read(const char *path, char *buf, u32 max)
{
    if (!buf || max == 0) return (u32)-1;

    u32 size = 0;
    const void *data = initrd_find(path, &size);
    if (!data) return (u32)-1;

    u32 n = size < max ? size : max;
    const u8 *src = (const u8 *)data;
    for (u32 i = 0; i < n; i++)
        buf[i] = (char)src[i];
    return n;
}
