#ifndef AETHER_INITRD_H
#define AETHER_INITRD_H

/*
 * AetherOS — Initial RAM Disk (initrd)
 *
 * The initrd is a CPIO newc archive embedded directly in the kernel binary.
 * It is linked in via an object file generated by aarch64-elf-objcopy:
 *
 *   objcopy -I binary -O elf64-littleaarch64 -B aarch64 initrd.cpio initrd.o
 *
 * This creates three linker symbols:
 *   _binary_initrd_cpio_start  — pointer to first byte of archive
 *   _binary_initrd_cpio_end    — pointer one past the last byte
 *   _binary_initrd_cpio_size   — size as an absolute symbol (use & to get addr)
 *
 * ── CPIO newc format ───────────────────────────────────────────────
 * Each entry:
 *   110-byte ASCII header  (magic "070701", fields in 8-digit hex)
 *   filename               (namesize bytes including NUL)
 *   padding                (to align header+filename to 4-byte boundary)
 *   file data              (filesize bytes)
 *   padding                (to align entry to 4-byte boundary)
 * Archive ends with an entry named "TRAILER!!!".
 */

#include "aether/types.h"

/*
 * initrd_init — validate the embedded archive and print a summary.
 * Must be called before initrd_find().
 */
void initrd_init(void);

/*
 * initrd_find — locate a file in the initrd by path.
 *
 * path:     file path, with or without leading '/'.  E.g. "/init" or "init".
 * size_out: if non-NULL, receives the file's size in bytes.
 *
 * Returns a pointer to the file's data (inside the kernel binary's .rodata),
 * or NULL if not found.  The data is read-only.
 */
const void *initrd_find(const char *path, u32 *size_out);

#endif /* AETHER_INITRD_H */
