/*
 * tls_aether.c — mbedTLS 3.6 wrapper for AetherOS (Iteration 3)
 *
 * Implements the API declared in tls_aether.h.
 *
 * Design notes:
 *
 *   Entropy:  No /dev/urandom on AetherOS.  We seed CTR-DRBG using
 *             mbedtls_hardware_poll() with a splitmix64 PRNG seeded from
 *             sys_rtc_get() XOR sys_get_ticks().  Not cryptographically
 *             strong, but sufficient for a hobby OS browser.
 *
 *   Cert verification: MBEDTLS_SSL_VERIFY_OPTIONAL — we log a warning but
 *             still connect even when cert verification fails (e.g. when
 *             QEMU RTC is 0 and cert dates can't be checked).
 *
 *   I/O model: Custom send/recv callbacks over the raw TCP fd.
 *             The fetcher's synchronous model (recv_all) means mbedTLS
 *             never gets WANT_READ from a non-blocking socket; the socket
 *             is blocking, so every read returns real data or EOF.
 *
 *   CA bundle: Embedded as g_ca_bundle[] in ca_bundle_gen.c (generated by
 *             scripts/fetch_mbedtls.sh from the Mozilla CA bundle).
 *             Parsed once in tls_global_init() into a static x509 chain.
 */

#include "tls_aether.h"

/* libaether_posix */
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <sys/socket.h>   /* send() / recv() */

/* AetherOS syscalls */
#include <sys.h>   /* sys_rtc_get(), sys_get_ticks() */

/* mbedTLS (included via vendor_mbedtls) */
#include <mbedtls/ssl.h>
#include <mbedtls/entropy.h>
#include <mbedtls/ctr_drbg.h>
#include <mbedtls/x509_crt.h>
#include <mbedtls/error.h>
#include <mbedtls/platform.h>
#include <mbedtls/platform_time.h>   /* mbedtls_ms_time_t */
#include <mbedtls/debug.h>

/* We excluded net_sockets.c (uses POSIX we don't want linked).
 * Define the small set of net error codes tls_aether.c uses directly. */
#ifndef MBEDTLS_ERR_NET_SEND_FAILED
#define MBEDTLS_ERR_NET_SEND_FAILED  (-0x004E)
#endif
#ifndef MBEDTLS_ERR_NET_RECV_FAILED
#define MBEDTLS_ERR_NET_RECV_FAILED  (-0x004C)
#endif
#ifndef MBEDTLS_ERR_NET_CONN_RESET
#define MBEDTLS_ERR_NET_CONN_RESET   (-0x0050)
#endif

/* CA bundle generated by fetch_mbedtls.sh */
extern const unsigned char g_ca_bundle[];
extern const size_t        g_ca_bundle_len;

/* ── UART debug helper ───────────────────────────────────────────────────── */

static void tls_uart(const char *s)
{
    long r;
    int len = 0;
    while (s[len]) len++;
    __asm__ volatile(
        "mov x8, #34\n mov x0, #1\n mov x1, %1\n mov x2, %2\n"
        "svc #0\n mov %0, x0\n"
        : "=r"(r) : "r"(s), "r"((long)len) : "x0","x1","x2","x8","memory"
    );
}

/* ── mbedTLS debug callback (level ≤ 2: errors + state changes) ─────────── */

static void tls_debug_cb(void *ctx, int level,
                          const char *file, int line, const char *str)
{
    (void)ctx; (void)file; (void)line;
    if (level <= 2) tls_uart(str);
}

/* ── mbedtls_ms_time() — MBEDTLS_PLATFORM_MS_TIME_ALT ───────────────────── */
/*
 * platform_util.c checks for POSIX (_POSIX_VERSION) or Windows.
 * Our freestanding env has neither, so we provide it here.
 * Returns monotonic milliseconds since boot via the 100 Hz tick counter.
 */
mbedtls_ms_time_t mbedtls_ms_time(void)
{
    return (mbedtls_ms_time_t)sys_get_ticks() * 10;  /* ticks → ms (100 Hz) */
}

/* ── Hardware entropy poll ───────────────────────────────────────────────── */
/*
 * Called by mbedtls_entropy_func() because MBEDTLS_ENTROPY_HARDWARE_ALT
 * is defined in mbedtls_aether_config.h.
 *
 * We use splitmix64 seeded from RTC + tick counter to fill the output buffer.
 * Each call advances the mixer state so repeated calls produce different bytes.
 */

static uint64_t s_entropy_state = 0;

int mbedtls_hardware_poll(void *data, unsigned char *output,
                          size_t len, size_t *olen)
{
    (void)data;

    /* Seed from hardware sources on first call (and refresh every call) */
    uint64_t seed = (uint64_t)sys_rtc_get()
                  ^ ((uint64_t)sys_get_ticks() << 32)
                  ^ (uint64_t)(uintptr_t)output;  /* pointer as jitter */
    s_entropy_state += seed + 0x9e3779b97f4a7c15ULL;

    size_t produced = 0;
    while (produced < len) {
        /* splitmix64 step */
        uint64_t z = s_entropy_state;
        z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9ULL;
        z = (z ^ (z >> 27)) * 0x94d049bb133111ebULL;
        z ^= z >> 31;
        s_entropy_state = z;

        size_t chunk = len - produced;
        if (chunk > sizeof(uint64_t)) chunk = sizeof(uint64_t);
        __builtin_memcpy(output + produced, &z, chunk);
        produced += chunk;
    }
    *olen = produced;
    return 0;
}

/* ── Custom I/O callbacks ────────────────────────────────────────────────── */

static int tls_bio_send(void *ctx, const unsigned char *buf, size_t len)
{
    int fd = *(int *)ctx;
    long n = (long)send(fd, buf, len, 0);
    if (n < 0) {
        tls_uart("tls_bio_send: send() returned -1\n");
        return MBEDTLS_ERR_NET_SEND_FAILED;
    }
    /* AetherOS send() returns 0 (success) instead of the byte count.
     * Map 0 → len so mbedTLS advances out_left correctly and doesn't
     * re-send the same record before every subsequent receive state. */
    if (n == 0) return (int)len;
    return (int)n;
}

static int tls_bio_recv(void *ctx, unsigned char *buf, size_t len)
{
    int fd = *(int *)ctx;
    long n = (long)recv(fd, buf, len, 0);
    if (n < 0) return MBEDTLS_ERR_NET_RECV_FAILED;
    if (n == 0) return MBEDTLS_ERR_SSL_CONN_EOF;
    return (int)n;
}

/* ── Global state ────────────────────────────────────────────────────────── */

static mbedtls_x509_crt  g_cacert;
static int                g_tls_init_done = 0;

/* ── tls_conn context ────────────────────────────────────────────────────── */

struct tls_conn {
    int                      fd;
    mbedtls_ssl_context      ssl;
    mbedtls_ssl_config       conf;
    mbedtls_entropy_context  entropy;
    mbedtls_ctr_drbg_context ctr_drbg;
};

/* ── Public API ──────────────────────────────────────────────────────────── */

void tls_global_init(void)
{
    if (g_tls_init_done) return;
    g_tls_init_done = 1;

    mbedtls_x509_crt_init(&g_cacert);

    /* Parse Mozilla CA bundle (PEM, null-terminated) */
    int ret = mbedtls_x509_crt_parse(&g_cacert, g_ca_bundle, g_ca_bundle_len);
    if (ret < 0) {
        tls_uart("tls_global_init: CA bundle parse FAILED\n");
    } else {
        tls_uart("tls_global_init: CA bundle loaded OK\n");
    }
}

tls_conn_t *tls_connect(int fd, const char *hostname)
{
    tls_conn_t *conn = calloc(1, sizeof(*conn));
    if (!conn) return NULL;

    conn->fd = fd;

    mbedtls_ssl_init(&conn->ssl);
    mbedtls_ssl_config_init(&conn->conf);
    mbedtls_entropy_init(&conn->entropy);
    mbedtls_ctr_drbg_init(&conn->ctr_drbg);

    int ret;

    /* Seed the DRBG from our hardware entropy source */
    static const unsigned char pers[] = "aether_browser_tls";
    ret = mbedtls_ctr_drbg_seed(&conn->ctr_drbg,
                                  mbedtls_entropy_func, &conn->entropy,
                                  pers, sizeof(pers) - 1);
    if (ret != 0) {
        tls_uart("tls_connect: ctr_drbg_seed failed\n");
        goto fail;
    }

    /* Load TLS 1.2 client defaults */
    ret = mbedtls_ssl_config_defaults(&conn->conf,
                                       MBEDTLS_SSL_IS_CLIENT,
                                       MBEDTLS_SSL_TRANSPORT_STREAM,
                                       MBEDTLS_SSL_PRESET_DEFAULT);
    if (ret != 0) {
        tls_uart("tls_connect: ssl_config_defaults failed\n");
        goto fail;
    }

    /* Wire debug callback (errors + state changes) */
    mbedtls_ssl_conf_dbg(&conn->conf, tls_debug_cb, NULL);
    mbedtls_debug_set_threshold(2);

    /* Wire RNG */
    mbedtls_ssl_conf_rng(&conn->conf,
                          mbedtls_ctr_drbg_random, &conn->ctr_drbg);

    /* Certificate verification — OPTIONAL so we still connect when:
     *   - QEMU RTC = 0 → cert dates check is skipped
     *   - CA bundle didn't parse fully
     * A failed verify is logged but does not abort the connection. */
    if (g_tls_init_done && g_cacert.raw.len > 0) {
        mbedtls_ssl_conf_ca_chain(&conn->conf, &g_cacert, NULL);
        mbedtls_ssl_conf_authmode(&conn->conf, MBEDTLS_SSL_VERIFY_OPTIONAL);
    } else {
        mbedtls_ssl_conf_authmode(&conn->conf, MBEDTLS_SSL_VERIFY_NONE);
    }

    /* Set up the SSL context */
    ret = mbedtls_ssl_setup(&conn->ssl, &conn->conf);
    if (ret != 0) {
        tls_uart("tls_connect: ssl_setup failed\n");
        goto fail;
    }

    /* SNI — required for virtual hosting (most HTTPS servers) */
    if (hostname) {
        ret = mbedtls_ssl_set_hostname(&conn->ssl, hostname);
        if (ret != 0) {
            tls_uart("tls_connect: ssl_set_hostname failed\n");
            goto fail;
        }
    }

    /* Wire our custom send/recv callbacks */
    mbedtls_ssl_set_bio(&conn->ssl, &conn->fd,
                         tls_bio_send, tls_bio_recv, NULL);

    /* Handshake loop (blocking socket — no WANT_READ in practice) */
    do {
        ret = mbedtls_ssl_handshake(&conn->ssl);
    } while (ret == MBEDTLS_ERR_SSL_WANT_READ ||
             ret == MBEDTLS_ERR_SSL_WANT_WRITE);

    if (ret != 0) {
        char errbuf[80];
        mbedtls_strerror(ret, errbuf, sizeof(errbuf));
        tls_uart("tls_connect v5: handshake FAILED: ");
        tls_uart(errbuf);
        /* print raw error code as hex so we can see any SSL high-level wrapper */
        {
            char hexbuf[16]; int hi = 0;
            unsigned int u = (unsigned int)(-ret);
            for (int shift = 28; shift >= 0; shift -= 4) {
                int n = (int)((u >> shift) & 0xf);
                if (n || hi) hexbuf[hi++] = (char)(n < 10 ? '0'+n : 'a'+n-10);
            }
            if (!hi) hexbuf[hi++] = '0';
            hexbuf[hi] = '\0';
            tls_uart(" (-0x");
            tls_uart(hexbuf);
            tls_uart(")\n");
        }
        goto fail;
    }

    /* Log cert verification result (non-fatal) */
    uint32_t flags = mbedtls_ssl_get_verify_result(&conn->ssl);
    if (flags != 0) {
        tls_uart("tls_connect: cert verify OPTIONAL failure (flags=");
        /* simple hex print */
        char tmp[16];
        int ti = 0;
        uint32_t f2 = flags;
        if (f2 == 0) { tmp[ti++] = '0'; }
        else {
            for (int shift = 28; shift >= 0; shift -= 4) {
                int nibble = (int)((f2 >> shift) & 0xf);
                if (nibble || ti) tmp[ti++] = (char)(nibble < 10 ? '0'+nibble : 'a'+nibble-10);
            }
        }
        tmp[ti] = '\0';
        tls_uart(tmp);
        tls_uart(") — continuing\n");
    } else {
        tls_uart("tls_connect: handshake OK\n");
    }

    return conn;

fail:
    tls_close(conn);
    return NULL;
}

int tls_write(tls_conn_t *conn, const void *buf, size_t len)
{
    size_t sent = 0;
    while (sent < len) {
        int ret = mbedtls_ssl_write(&conn->ssl,
                                     (const unsigned char *)buf + sent,
                                     len - sent);
        if (ret == MBEDTLS_ERR_SSL_WANT_WRITE ||
            ret == MBEDTLS_ERR_SSL_WANT_READ)
            continue;
        if (ret <= 0) return -1;
        sent += (size_t)ret;
    }
    return (int)sent;
}

int tls_read(tls_conn_t *conn, void *buf, size_t len)
{
    int ret = mbedtls_ssl_read(&conn->ssl, (unsigned char *)buf, len);
    if (ret == MBEDTLS_ERR_SSL_WANT_READ ||
        ret == MBEDTLS_ERR_SSL_WANT_WRITE)
        return 0;
    if (ret == MBEDTLS_ERR_SSL_CONN_EOF ||
        ret == MBEDTLS_ERR_NET_CONN_RESET ||
        ret == 0)
        return 0;
    if (ret < 0) return -1;
    return ret;
}

uint8_t *tls_read_all(tls_conn_t *conn, size_t *out_len)
{
    size_t cap = 32768, used = 0;
    uint8_t *buf = malloc(cap);
    if (!buf) return NULL;

    while (1) {
        if (used + 4096 > cap) {
            cap *= 2;
            uint8_t *nb = realloc(buf, cap);
            if (!nb) { free(buf); return NULL; }
            buf = nb;
        }
        int n = mbedtls_ssl_read(&conn->ssl, buf + used, cap - used - 1);
        if (n == MBEDTLS_ERR_SSL_WANT_READ ||
            n == MBEDTLS_ERR_SSL_WANT_WRITE)
            continue;
        if (n <= 0) break;   /* EOF or error — done */
        used += (size_t)n;
    }
    buf[used] = '\0';
    *out_len = used;
    return buf;
}

void tls_close(tls_conn_t *conn)
{
    if (!conn) return;
    mbedtls_ssl_close_notify(&conn->ssl);
    mbedtls_ssl_free(&conn->ssl);
    mbedtls_ssl_config_free(&conn->conf);
    mbedtls_entropy_free(&conn->entropy);
    mbedtls_ctr_drbg_free(&conn->ctr_drbg);
    free(conn);
}
