#!/bin/bash
# scripts/fetch_netsurf_libs.sh — Download all NetSurf support libraries
#
# Libraries (in dependency order):
#   libparserutils 0.2.5  — charset encoding, input streams
#   libwapcaplet   0.4.3  — string interning
#   libnsutils     0.1.1  — base64, time utilities
#   libnsbmp       0.1.7  — BMP decoder
#   libnsgif       1.0.0  — GIF decoder
#   libhubbub      0.3.8  — HTML5 parser (needs libparserutils)
#   libcss         0.9.2  — CSS parser + selector (needs libparserutils, libwapcaplet)
#   libdom         0.4.2  — DOM (needs libhubbub, libwapcaplet, libparserutils)
#
# Run once before building:  scripts/fetch_netsurf_libs.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VENDOR_DIR="${SCRIPT_DIR}/../userspace/vendor"
BASE_URL="https://download.netsurf-browser.org/libs/releases"
CACHE_DIR="/tmp/netsurf-src"

mkdir -p "${CACHE_DIR}"

fetch_lib() {
    local name="$1"
    local ver="$2"
    local tarball="${name}-${ver}-src.tar.gz"
    local cache="${CACHE_DIR}/${tarball}"
    local dest="${VENDOR_DIR}/${name}"

    echo "[netsurf] Fetching ${name} ${ver}..."
    if [ ! -f "${cache}" ]; then
        curl -fL -o "${cache}" "${BASE_URL}/${tarball}"
    else
        echo "[netsurf]   (cached)"
    fi

    rm -rf "${dest}"
    mkdir -p "${VENDOR_DIR}"
    tar -xzf "${cache}" -C "${VENDOR_DIR}"
    mv "${VENDOR_DIR}/${name}-${ver}" "${dest}"
    echo "[netsurf]   → ${dest}"
}

fetch_lib libparserutils 0.2.5
fetch_lib libwapcaplet   0.4.3
fetch_lib libnsutils     0.1.1
fetch_lib libnsbmp       0.1.7
fetch_lib libnsgif       1.0.0
fetch_lib libhubbub      0.3.8
fetch_lib libcss         0.9.2
fetch_lib libdom         0.4.2

echo ""
echo "[netsurf] Generating libparserutils aliases.inc..."
(cd "${VENDOR_DIR}/libparserutils" && perl build/make-aliases.pl)
echo "[netsurf]   → src/charset/aliases.inc"

echo "[netsurf] Generating libhubbub entities.inc..."
(cd "${VENDOR_DIR}/libhubbub" && perl build/make-entities.pl)
echo "[netsurf]   → src/tokeniser/entities.inc"

echo "[netsurf] Generating libhubbub autogenerated-element-type.c (gperf)..."
gperf "${VENDOR_DIR}/libhubbub/src/treebuilder/element-type.gperf" \
    > "${VENDOR_DIR}/libhubbub/src/treebuilder/autogenerated-element-type.c"
echo "[netsurf]   → src/treebuilder/autogenerated-element-type.c"

echo ""
echo "[netsurf] All libraries fetched — run: ninja -C build"
