#!/usr/bin/env bash
# fetch_mbedtls.sh — Download mbedTLS 3.6.2 + Mozilla CA bundle (Iteration 3)
#
# Outputs:
#   userspace/vendor/mbedtls/          — mbedTLS source (gitignored)
#   userspace/lib/netsurf_aether/ca_bundle_gen.c  — CA bundle as C source (tracked)
#
# Run once before building:
#   scripts/fetch_mbedtls.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$SCRIPT_DIR/.."
DEST="$ROOT/userspace/vendor/mbedtls"
CA_GEN_C="$ROOT/userspace/lib/netsurf_aether/ca_bundle_gen.c"

MBEDTLS_VERSION="3.6.2"
MBEDTLS_URL="https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-${MBEDTLS_VERSION}/mbedtls-${MBEDTLS_VERSION}.tar.bz2"
CA_BUNDLE_URL="https://curl.se/ca/cacert.pem"

# ── mbedTLS source ────────────────────────────────────────────────────────────

if [ -d "$DEST/include/mbedtls" ]; then
    echo "[mbedTLS] Already present at $DEST — skipping download."
else
    echo "[mbedTLS] Downloading mbedTLS ${MBEDTLS_VERSION}..."
    TMP_TAR="/tmp/mbedtls-${MBEDTLS_VERSION}.tar.bz2"
    curl -fL "$MBEDTLS_URL" -o "$TMP_TAR"

    echo "[mbedTLS] Extracting..."
    TMP_DIR="/tmp/mbedtls_extract_$$"
    mkdir -p "$TMP_DIR"
    tar -xjf "$TMP_TAR" -C "$TMP_DIR"

    # Move the extracted directory to our destination
    EXTRACTED="$(ls "$TMP_DIR")"
    mv "$TMP_DIR/$EXTRACTED" "$DEST"
    rm -rf "$TMP_DIR" "$TMP_TAR"

    echo "[mbedTLS] Extracted to $DEST"
fi

# ── Mozilla CA bundle → ca_bundle_gen.c ──────────────────────────────────────

echo "[mbedTLS] Downloading Mozilla CA bundle..."
TMP_CA="/tmp/cacert_$$.pem"
curl -fL "$CA_BUNDLE_URL" -o "$TMP_CA"

CA_SIZE=$(wc -c < "$TMP_CA" | tr -d ' ')
echo "[mbedTLS] CA bundle: ${CA_SIZE} bytes → generating ca_bundle_gen.c"

python3 - "$TMP_CA" "$CA_GEN_C" <<'EOF'
import sys, os

src  = sys.argv[1]
dest = sys.argv[2]

data = open(src, 'rb').read()
n    = len(data)

lines = ['/* Auto-generated by fetch_mbedtls.sh — do not edit. */',
         '/* Mozilla CA root bundle — embedded as a null-terminated PEM string. */',
         '#include <stddef.h>',
         '',
         'const unsigned char g_ca_bundle[] = {']

# 16 bytes per line
for i in range(0, n, 16):
    chunk = data[i:i+16]
    hex_str = ', '.join(f'0x{b:02x}' for b in chunk) + ','
    lines.append(f'    {hex_str}')

# Null terminator
lines.append('    0x00')
lines.append('};')
lines.append(f'const size_t g_ca_bundle_len = {n + 1};  /* includes null terminator */')

os.makedirs(os.path.dirname(dest), exist_ok=True)
open(dest, 'w').write('\n'.join(lines) + '\n')
EOF

rm -f "$TMP_CA"

echo "[mbedTLS] ca_bundle_gen.c written to $CA_GEN_C"
echo ""
echo "Done! Next step:"
echo "  ninja -C build"
